[package]
name = "my_todo_list"
version = "1.0.0"
authors = []

[addresses]
todolist_addr='6d6be1b9c3ba4e2c249285781f6213833cfd6017569480771e94acaf3664b0a6'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
